apiVersion: v1
kind: Pod
metadata:
  name: workload-1
  labels:
    ml.scheduler/run-id: run-heterogeneous
  annotations:
    ml.scheduler/run-id: run-heterogeneous
    ml.scheduler/estimated-training-time: "300"
    ml.scheduler/loss-reduction-rate: "0.1"
    ml.scheduler/matrix-size: "1024"
    ml.scheduler/gradient-update-size: "256"
    ml.scheduler/checkpoint-interval: "100"
    ml.scheduler/model-partitions: "1"
spec:
  schedulerName: default-scheduler
  schedulingGates:
  - name: ml.scheduler/release
  containers:
  - name: train
    image: nginx
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"