apiVersion: v1
kind: Pod
metadata:
  name: workload-3
  labels:
    ml.scheduler/run-id: run-medium
  annotations:
    ml.scheduler/run-id: run-medium
    ml.scheduler/estimated-training-time: "400"
    ml.scheduler/loss-reduction-rate: "0.05"
    ml.scheduler/matrix-size: "2048"
    ml.scheduler/gradient-update-size: "512"
    ml.scheduler/checkpoint-interval: "200"
    ml.scheduler/model-partitions: "1"
spec:
  schedulerName: default-scheduler
  schedulingGates:
  - name: ml.scheduler/release
  containers:
  - name: train
    image: nginx
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "2Gi"
        cpu: "2000m"